version: "2.2"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: server
    depends_on: 
      - database
    links: 
      - database
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: client
    depends_on: 
      - server
    links: 
      - server
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
  database:
    image: mysql:5.7
    restart: always
    container_name: database
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
