version: "3"
services:
  dashboard-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: dashboard-server
    depends_on: 
      - dashboard-database
    links: 
      - dashboard-database
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
  dashboard-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: dashboard-client
    depends_on: 
      - dashboard-server
    links: 
      - dashboard-server
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
  dashboard-database:
    image: mysql:5.7
    restart: always
    container_name: dashboard-database
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 5