version: "2.2"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: server
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
  database:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3307:3306
    volumes:
      - ./database:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
