CREATE DATABASE IF NOT EXISTS DashboardDatabase;

USE DashboardDatabase;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  mail VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);